import { type FichaDto, FichaClasse } from "typesrc/dtos/ficha/ficha.dto";

export const fichas: FichaDto[] = [
    {
        id: 1,
        nome: "R0D",
        avatar: "/img/pages/sessao/snake.png",
        personagem: "Snake",
        classe: FichaClasse.guerreiro,
        historia: "Snake é um guerreiro lendário, conhecido por sua bravura e habilidades em combate. Ele viaja pelo mundo em busca de aventuras e desafios.",
        vidas: 12,
        vidasTotal: 19,
        magia: 365,
        experiencia: 1000,
        itens: ["Espada", "Escudo", "Poção de Cura"],
        golpes: ["Ataque Poderoso", "Defesa Inabalável", "Golpe Rápido"],
        tiposDano: ["Corte", "Impacto", "Mágico"],
        forca: 59,
        habilidade: 50,
        resistencia: 20,
        armadura: 100,
        poder: 100,
        pontos: 1265
    },
    {
        id: 2,
        nome: "S4m9999",
        avatar: "/img/pages/sessao/oz.png",
        personagem: "Oz De Ousborne",
        classe: FichaClasse.mago,
        historia: "Oz é um mago poderoso, conhecido por sua sabedoria e habilidades arcanas. Ele busca o conhecimento e a verdade em um mundo repleto de mistérios.",
        vidas: 17,
        vidasTotal: 24,
        magia: 569,
        experiencia: 1500,
        itens: ["Cajado Mágico", "Livro de Feitiços", "Poção de Mana"],
        golpes: ["Bola de Fogo", "Escudo Mágico", "Teleporte"],
        tiposDano: ["Fogo", "Gelo", "Elétrico"],
        forca: 30,
        habilidade: 45,
        resistencia: 15,
        armadura: 80,
        poder: 120,
        pontos: 1236
    },
    {
        id: 3,
        nome: "LRondamGamer777",
        avatar: "/img/pages/sessao/blaze.png",
        personagem: "Blaze of Glory",
        classe: FichaClasse.paladino,
        historia: "Blaze é um paladino destemido, defensor da justiça e da luz. Ele luta contra as forças das trevas para proteger os inocentes e restaurar a paz.",
        vidas: 18,
        vidasTotal: 25,
        magia: 450,
        experiencia: 1200,
        itens: ["Martelo Sagrado", "Escudo Divino", "Poção de Vida"],
        golpes: ["Golpe Divino", "Escudo Protetor", "Investida Sagrada"],
        tiposDano: ["Corte", "Impacto", "Mágico"],
        forca: 65,
        habilidade: 55,
        resistencia: 25,
        armadura: 120,
        poder: 110,
        pontos: 1350
    },
    {
        id: 4,
        nome: "XxNicholasxX",
        avatar: "/img/pages/sessao/bardo.png",
        personagem: "Bardo Flowers",
        classe: FichaClasse.bardo,
        historia: "Bardo é um músico encantador, cujas canções inspiram e curam. Ele viaja pelo mundo espalhando alegria e esperança através de sua música.",
        vidas: 15,
        vidasTotal: 22,
        magia: 400,
        experiencia: 1100,
        itens: ["Lira Mágica", "Instrumento Musical", "Poção de Alegria"],
        golpes: ["Canção de Cura", "Melodia Encantadora", "Ritmo Acelerado"],
        tiposDano: ["Sônico", "Mágico", "Psíquico"],
        forca: 40,
        habilidade: 55,
        resistencia: 15,
        armadura: 85,
        poder: 95,
        pontos: 1200
    }
]